### ISSUE TITLE
Issues with Burrito!! 

### ISSUE THREAD

**Issue by lucassea** [IntroToCode/RecipesCodemates4#4]
## 💬 Discussion topic
Breakfast

Breakfast
## ❗ Potential issues
We need to have lactose free options and a super hot salsa sauce !

## 👥 People to consult

@FlyingOreo
@ryosuke1224-haas
@geo8892
@lucassea

## 📃 Details

Add lactose free cheese option and a california reaper salsa sauce

**Comment by d27-c** [comment]
hahahahah. true. agreed.

**Comment by geo8892** [comment]
True true, let me modify!

**Comment by geo8892** [comment]
Included Diary Free Cheese and california reaper salsa sauce to ingredients! Let me know if I can close this issue. 

@FlyingOreo @ryosuke1224-haas @lucassea

**Comment by FlyingOreo** [comment]
Looks good to close!
