### ISSUE TITLE
One more ingredients need for Hot dog

### ISSUE THREAD

**Issue by ryosuke1224-haas** [IntroToCode/RecipesCodemates4#5]
## 💬 Discussion topic
Need more ingredients
## ❗ Potential issues
Important ingredient is missing
## 👥 People to consult
@FlyingOreo
@ryosuke1224-haas
@geo8892
@lucassea
## 📃 Details
we need a relish for ingredients

**Comment by d27-c** [comment]
@FlyingOreo do you want to resolve?

**Comment by ryosuke1224-haas** [comment]
resolved
