### ISSUE TITLE
Concern about use of cheese 

### ISSUE THREAD

**Issue by d27-c** [IntroToCode/RecipesCodemates4#6]
## 💬 Discussion topic

I don't think that people eat hot dogs with cheese. 

## ❗ Potential issues

This cheese reference should be removed. 

## 👥 People to consult

@FlyingOreo 

## 📃 Details

Text

**Comment by lucassea** [comment]
I agree!

**Comment by geo8892** [comment]
Has this issue been resolved?

**Comment by FlyingOreo** [comment]
Cheese has been removed and resolved!
